#import "./../templates/pageheader.typ": *
#import "./../templates/pagefooter.typ": *
#import "./../templates/sectionheadingbox.typ": *
#import "./../templates/warningbox.typ": *
#import "./../templates/indent.typ": *
#import "./../templates/smallheading.typ": *
#import "./../templates/item.typ": *
#import "./../templates/squaredot.typ": *
#import "./../templates/rounddot.typ": *
#import "./../templates/L1.typ": *
#import "./../templates/L2.typ": *
#import "./../templates/L3.typ": *
#import "./../templates/italic.typ": *
#import "./../templates/red.typ": *
#import "./../templates/green.typ": *
#import "./../templates/tasksharingtable.typ": *
#import "./../templates/combinedcell.typ": *
#import "./../templates/optiontriangle.typ": *
